import { Command } from "commander";
import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join, resolve } from "path";

interface Template {
  name: string;
  description: string;
  builtin: boolean;
  generate: (dir: string, projectName: string) => void;
}

const BUILTIN_TEMPLATES: Template[] = [
  {
    name: "empty",
    description: "Empty 3D project with just a root node",
    builtin: true,
    generate: (dir, name) => {
      writeFileSync(
        join(dir, "project.godot"),
        projectGodot(name, "res://main.tscn")
      );
      writeFileSync(join(dir, "main.tscn"), emptyScene());
    },
  },
  {
    name: "3d-basic",
    description: "3D scene with camera, light, and floor",
    builtin: true,
    generate: (dir, name) => {
      writeFileSync(
        join(dir, "project.godot"),
        projectGodot(name, "res://main.tscn")
      );
      writeFileSync(join(dir, "main.tscn"), basicScene3D());
    },
  },
];

export const createCommand = new Command("create")
  .description("Create a new Summer Engine project from a template")
  .argument("<template>", `Template name (${BUILTIN_TEMPLATES.map((t) => t.name).join(", ")})`)
  .argument("[name]", "Project directory name (defaults to template name)")
  .action(async (templateName: string, projectName?: string) => {
    const template = BUILTIN_TEMPLATES.find((t) => t.name === templateName);

    if (!template) {
      console.error(`Unknown template: ${templateName}`);
      console.log("\nAvailable templates:");
      for (const t of BUILTIN_TEMPLATES) {
        console.log(`  ${t.name.padEnd(12)} ${t.description}`);
      }
      console.log("\nMore templates coming soon at github.com/summerengine/templates");
      process.exit(1);
    }

    const dirName = projectName || templateName;
    const fullPath = resolve(dirName);

    if (existsSync(fullPath)) {
      console.error(`Directory already exists: ${fullPath}`);
      process.exit(1);
    }

    console.log(`Creating project from '${templateName}' template...`);
    mkdirSync(fullPath, { recursive: true });
    template.generate(fullPath, dirName);

    console.log(`\nProject created at ${fullPath}`);
    console.log("\nNext steps:");
    console.log(`  summer run ${dirName}`);
  });

function projectGodot(name: string, mainScene: string): string {
  return `; Summer Engine Project
; Generated by summer-engine CLI

[application]

config/name="${name}"
run/main_scene="${mainScene}"
config/features=PackedStringArray("4.5")

[rendering]

renderer/rendering_method="forward_plus"
`;
}

function emptyScene(): string {
  return `[gd_scene format=3]

[node name="World" type="Node3D"]
`;
}

function basicScene3D(): string {
  return `[gd_scene load_steps=4 format=3]

[sub_resource type="BoxMesh" id="BoxMesh_floor"]
size = Vector3(20, 0.2, 20)

[sub_resource type="StandardMaterial3D" id="StandardMaterial3D_floor"]
albedo_color = Color(0.4, 0.45, 0.4, 1)

[sub_resource type="ProceduralSkyMaterial" id="ProceduralSkyMaterial_sky"]

[node name="World" type="Node3D"]

[node name="Camera3D" type="Camera3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 0.939693, 0.34202, 0, -0.34202, 0.939693, 0, 5, 10)

[node name="DirectionalLight3D" type="DirectionalLight3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 0.866025, 0.5, 0, -0.5, 0.866025, 0, 8, 0)
shadow_enabled = true

[node name="Floor" type="MeshInstance3D" parent="."]
mesh = SubResource("BoxMesh_floor")
surface_material_override/0 = SubResource("StandardMaterial3D_floor")

[node name="WorldEnvironment" type="WorldEnvironment" parent="."]
`;
}
